apiVersion: v1
kind: Secret
metadata:
  name: pdf-reports-secret
  namespace: pdf-reports
type: Opaque
stringData:
  POSTGRES_USER: "report_user"
  POSTGRES_PASSWORD: "report_password"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
